import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.css";
import ClientWrapper from "./components/ClientWrapper";
import Navbar from "./components/navbar";
import Footer from "./components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 

{
    
  return (
     <html lang="en" className="h-full antialiased">
      <body>
          
          <ClientWrapper>
            <Navbar />
            <main>{children}</main>
            <Footer />
          </ClientWrapper>
      </body>
    </html>
  );
}
